### ISSUE TITLE
Users without edit rights can change a page through the MediaWiki API

### ISSUE THREAD

**Issue by nathancarter** [nischayn22/ArticleProtection#1]
Let's say user X does not have permission to edit page Y.  User X can still use the [login API documented here](https://www.mediawiki.org/wiki/API:Login) and then [the edit API documented here](https://www.mediawiki.org/wiki/API:Edit) to attempt to edit page Y.  In such a circumstance, the edit succeeds, even when it should not.

Does `ArticleProtection` just turn off the UI elements for editing the page in the wiki interface itself?  Could it be made to also prevent edits from the MediaWiki API, as in the case above?

**Comment by nathancarter** [comment]
I am not a MediaWiki extension developer, but I read a few docs and it seems that the missing hook is [APIEditBeforeSave](https://www.mediawiki.org/wiki/Manual:Hooks/APIEditBeforeSave), which is "Called right before saving an edit submitted through `api.php?action=edit`" and you can "Return true to continue processing, return false to abort processing and reject the edit."  Therefore it may be that a simple addition to [ArticleProtection.hooks.php](https://github.com/nischayn22/ArticleProtection/blob/master/ArticleProtection.hooks.php) to handle this hook would suffice.  What do you think?

**Comment by nathancarter** [comment]
I just created a branch/pull request that solves this issue.  Wasn't too hard, imitating your other code.  Please feel free to test and merge if you like it.  Thanks!

**Comment by nischayn22** [comment]
Sorry didn't find enough time to look at this. Will merge it soon.

sent from my Nexus
Nischay

**Comment by nischayn22** [comment]
I have merged this without testing. If you find a bug later please do push your fixes if any. Thanks for the contribution. Also feel free to add a README file with your name in Credits if you wish to :+1:

**Comment by nathancarter** [comment]
Thanks for the quick reply!  No credits needed.
